[package]
name = "lp-solvers"
version = "0.5.0"
authors = ["Joel Cavat <jcavat@gmail.com>"]
description = ".lp file format implementation and external solver invocation functions such as CBC, Gurobi, lp_solve, ..."
repository = "https://github.com/jcavat/rust-lp-modeler"
readme = "README.md"
license = "MIT"
keywords = ["linear-programming", "linear-models", "optimization", "solver", "formulation" ]
documentation = "https://jcavat.github.io/rust-lp-modeler"
edition = "2018"

exclude = [
    "src/main.rs",
    "*.yml",
    "*.gitignore",
    "*.log",
    "*.iml",
    ".lp",
    "doc/*",
    "Cargo.lock",
]

[dependencies]
tempfile = "3"
