name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test_linux:
    name: Test Linux Default
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v2
    - uses: Swatinem/rust-cache@v2
    - name: install dependencies
      run:  |
        sudo apt install coinor-cbc
    - name: Build
      run: cargo test --no-run --verbose --all-features
    - name: Clippy
      run: cargo clippy --all-features -- -D warnings
    - name: Run tests
      run: cargo test --verbose
  
  test_windows:
    name: Test Windows Default
    runs-on: windows-latest    
    steps:
    - uses: actions/checkout@v2
    - uses: Swatinem/rust-cache@v2
    - name: install dependencies
      run:  |
        mkdir C:\Cbc
        curl https://www.coin-or.org/download/binary/Cbc/Cbc-2.10-win64-msvc16-mdd.zip --output Cbc-2.10.zip
        7z x "Cbc-2.10.zip" -o"Cbc"
        $SUB= '' + (Get-Location) + '\Cbc\bin'
        echo $SUB
        echo $SUB | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
